import { Product, Customer, Supplier, InventoryBatch } from "@/types";
import { generateId } from "./storage";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: generateId(),
    name: "Dairy Meal 70kg",
    description: "High protein dairy meal for cattle",
    category: "feeds",
    sku: "FM-001",
    barcode: "5901234123457",
    unit: "bags",
    retailPrice: 3500,
    wholesalePrice: 3200,
    costPrice: 2800,
    reorderLevel: 10,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Chick Mash 25kg",
    description: "Starter feed for chicks",
    category: "poultry",
    sku: "PM-001",
    unit: "bags",
    retailPrice: 2200,
    wholesalePrice: 2000,
    costPrice: 1800,
    reorderLevel: 15,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "NPK Fertilizer 50kg",
    description: "Compound fertilizer for crops",
    category: "fertilizers",
    sku: "FT-001",
    unit: "bags",
    retailPrice: 4500,
    wholesalePrice: 4200,
    costPrice: 3800,
    reorderLevel: 20,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Duduthrin 1L",
    description: "General purpose insecticide",
    category: "pesticides",
    sku: "PS-001",
    unit: "bottles",
    retailPrice: 850,
    wholesalePrice: 750,
    costPrice: 600,
    reorderLevel: 25,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Roundup 1L",
    description: "Non-selective herbicide",
    category: "herbicides",
    sku: "HB-001",
    unit: "bottles",
    retailPrice: 1200,
    wholesalePrice: 1050,
    costPrice: 900,
    reorderLevel: 20,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Ivermectin 50ml",
    description: "Anti-parasitic for livestock",
    category: "veterinary",
    sku: "VT-001",
    unit: "bottles",
    retailPrice: 650,
    wholesalePrice: 550,
    costPrice: 450,
    reorderLevel: 30,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Hybrid Maize Seeds 2kg",
    description: "High yield maize variety",
    category: "seeds",
    sku: "SD-001",
    unit: "packets",
    retailPrice: 450,
    wholesalePrice: 400,
    costPrice: 320,
    reorderLevel: 50,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Albendazole 10%",
    description: "Dewormer for livestock",
    category: "veterinary",
    sku: "VT-002",
    unit: "bottles",
    retailPrice: 450,
    wholesalePrice: 380,
    costPrice: 300,
    reorderLevel: 25,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_CUSTOMERS: Customer[] = [
  {
    id: generateId(),
    name: "John Mwangi",
    phone: "+254712345678",
    email: "john@example.com",
    address: "Kiambu, Kenya",
    customerType: "retail",
    creditLimit: 50000,
    currentBalance: 0,
    loyaltyPoints: 150,
  },
  {
    id: generateId(),
    name: "Mary Wanjiku",
    phone: "+254723456789",
    address: "Thika, Kenya",
    customerType: "wholesale",
    creditLimit: 200000,
    currentBalance: 15000,
    loyaltyPoints: 500,
  },
  {
    id: generateId(),
    name: "Peter Ochieng",
    phone: "+254734567890",
    email: "peter@farmersgroup.co.ke",
    address: "Nakuru, Kenya",
    customerType: "vip",
    creditLimit: 500000,
    currentBalance: 0,
    loyaltyPoints: 2000,
  },
];

export const SAMPLE_SUPPLIERS: Supplier[] = [
  {
    id: generateId(),
    name: "Unga Holdings Ltd",
    contactPerson: "James Kamau",
    phone: "+254720111222",
    email: "supplies@unga.co.ke",
    address: "Industrial Area, Nairobi",
    paymentTerms: "Net 30",
    active: true,
  },
  {
    id: generateId(),
    name: "Osho Chemicals",
    contactPerson: "Sarah Akinyi",
    phone: "+254721333444",
    email: "orders@osho.co.ke",
    address: "Mombasa Road, Nairobi",
    paymentTerms: "Net 14",
    active: true,
  },
  {
    id: generateId(),
    name: "Kenya Seed Company",
    contactPerson: "David Kiprop",
    phone: "+254722555666",
    email: "sales@kenyaseed.co.ke",
    address: "Kitale, Kenya",
    paymentTerms: "Net 30",
    active: true,
  },
];

export const generateSampleBatches = (products: Product[]): InventoryBatch[] => {
  const batches: InventoryBatch[] = [];
  const today = new Date();
  
  products.forEach((product, index) => {
    const expiryDate = new Date(today);
    expiryDate.setMonth(expiryDate.getMonth() + 6 + index);
    
    batches.push({
      id: generateId(),
      productId: product.id,
      batchNumber: `BATCH-${Date.now()}-${index}`,
      quantity: Math.floor(Math.random() * 50) + 10,
      expiryDate: expiryDate.toISOString(),
      purchaseDate: today.toISOString(),
      costPerUnit: product.costPrice,
    });
  });
  
  return batches;
};
